"""M4 cover letters: text + one-page PDF, generated by Claude, checked by code.

Rules (plan.md, "Cover letters"):
  - 3 short paragraphs, 150-250 words, plain and specific. Tone comes from writing_samples.txt; facts come
    ONLY from the visible resume content (never from the samples, never invented).
  - The guard is code, not the LLM: word count, paragraph count, banned phrases (cover_letter.yaml), every
    number must exist on the visible resume, every technology named must be on the visible resume, no
    sensitive topics (salary, visa, notice, relocation, EEO), no placeholders or markdown.
  - A letter that fails is regenerated ONCE, with the reasons. Still failing -> no letter: an optional field is
    left empty, a required field switches that application to assist mode (handled in answers.py).
  - Every attempt is saved in the job folder.
"""
from __future__ import annotations

import json
import re
from datetime import date
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

import yaml

import guard
from jobbot.answers import visible_text

ROOT = Path(__file__).resolve().parents[1]
CONFIG_FILE = ROOT / "cover_letter.yaml"
SAMPLES_FILE = ROOT / "writing_samples.txt"
SAMPLES_EXAMPLE = ROOT / "writing_samples.example.txt"
MODEL_FILE = ROOT / "cover_letter_model.txt"        # the user's own letter: the MAIN style model (gitignored)

_SENSITIVE = re.compile(r"\b(salary|ctc|lpa|lakhs?|compensation|visa|sponsor\w*|work permit|notice period|"
                        r"relocat\w*|gender|ethnic\w*|veteran|disabilit\w*|authori[sz]ed to work|"
                        r"criminal|citizenship)\b", re.I)
# Statements about the candidate himself or about results that the resume does not make. The resume bullets are
# the only source of facts, so feelings, lessons and unstated outcomes are claims too.
_SELF_CLAIM = re.compile(r"\b(taught me|i (have )?learn(ed|t)|learn(ed|t) to|i (really |truly )?(love|like|enjoy|care about|"
                         r"believe|pride myself)|my passion|i am (someone|a person|a (quick|fast) learner)|"
                         r"(much|significantly|dramatically|greatly|vastly) (faster|better|easier|more (reliable|efficient)))\b", re.I)
MIN_QUOTES = 2
MAX_FIRST_PARAGRAPH_SENTENCES = 2     # default for cfg["first_paragraph"]["max_sentences"]
_PLACEHOLDER = re.compile(r"\[[^\]\n]{1,40}\]|<[^>\n]{1,40}>|\{\{|\}\}|\bTODO\b|lorem ipsum", re.I)
# Words that make a statement about the company bigger than the job description made it ("the world's logistics
# networks"). A letter may use one only if the JD itself does.
_BROADENING = {"world", "worlds", "world's", "worldwide", "global", "globally", "international", "internationally",
               "entire", "everyone", "everything", "everywhere", "always", "industry", "leading", "largest", "biggest",
               "best", "top", "premier", "millions", "billions", "countless", "unmatched", "unrivalled", "unrivaled"}
# Comparatives that state a result ("faster debugging"). The resume is the only source of results, so the letter may
# use one only if the visible resume uses that word.
_OUTCOME_WORDS = {"faster", "quicker", "easier", "simpler", "safer", "cheaper", "smoother", "better", "improved",
                  "reduced", "fewer", "less", "speed", "speeds", "quickly", "efficiency", "efficient", "streamlined",
                  "accelerate", "accelerated", "boost", "boosted", "enhances", "improves", "reduces"}
COPY_SPAN = 8                      # words in a row copied from a style sample / model letter
_GREETING = re.compile(r"\s*(dear|hi|hello|hey|greetings)\b", re.I)
_QUOTE_MARKS = re.compile('["“”„‟«»]')
MAX_ACHIEVEMENT_SENTENCES = 2     # default for cfg["achievements"]["max_sentences_with_numbers"]
_MARKDOWN = re.compile(r"(^|\n)\s*([#>*\-] |\d+\. )|\*\*|`|__")
_WORD = re.compile(r"[A-Za-z0-9][A-Za-z0-9'’+#./-]*")


@dataclass
class LetterResult:
    text: str | None
    ok: bool
    attempts: list[dict] = field(default_factory=list)       # [{"text":..., "problems": [...]}]

    @property
    def problems(self) -> list[str]:
        return self.attempts[-1]["problems"] if self.attempts else []


def load_config(path: Path = CONFIG_FILE) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def parse_samples(text: str) -> list[str]:
    body = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("#"))
    parts = re.split(r"^=== Sample[^\n]*$", body, flags=re.M)
    return [p.strip() for p in parts[1:] if p.strip()]


def load_samples(path: Path = SAMPLES_FILE) -> tuple[list[str], str]:
    """(samples, which file). Falls back to the made-up example, which still shows the format."""
    if path.exists():
        return parse_samples(path.read_text(encoding="utf-8")), path.name
    return parse_samples(SAMPLES_EXAMPLE.read_text(encoding="utf-8")), SAMPLES_EXAMPLE.name


def load_model(path: Path = MODEL_FILE) -> str:
    """The user's own cover letter, if they saved one (comment lines starting with # are dropped), else "". There is
    no made-up fallback: with no file the samples alone set the tone."""
    try:
        text = path.read_text(encoding="utf-8") if path.exists() else ""
    except OSError:
        return ""
    return "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("#")).strip()


def _norm(s: str) -> str:
    return s.replace("’", "'").replace("‘", "'").casefold()


def words(text: str) -> list[str]:
    return _WORD.findall(text)


def paragraphs(text: str) -> list[str]:
    return [p.strip() for p in re.split(r"\n\s*\n", text.strip()) if p.strip()]


def last_sentence(text: str) -> str:
    """The final sentence of the letter body (its closing line)."""
    parts = re.split(r"(?<=[.!?])\s+", paragraphs(text)[-1]) if paragraphs(text) else [""]
    return parts[-1].strip()


_BARE_THANKS = re.compile(r"^\W*thank(s| you)\b[^,;:]*$", re.I)


def closing_line(text: str) -> str:
    """What makes a letter's ending its own: the last sentence that is not a bare thank-you. Nearly every letter ends
    with some "Thank you ...", so comparing those would reject every letter once a few exist; the sentence before
    the thanks is what has to differ. A letter that is only thanks falls back to its last sentence."""
    paras = paragraphs(text)
    sentences = [x.strip() for x in re.split(r"(?<=[.!?])\s+", paras[-1]) if x.strip()] if paras else []
    for sentence in reversed(sentences):
        if not _BARE_THANKS.match(sentence):
            return sentence
    return last_sentence(text)


def choose_closing(cfg: dict, company: str, role: str, recent_styles: list[str]) -> str:
    """A closing style that differs from the letters written most recently. Deterministic for a given job."""
    import hashlib
    styles = cfg.get("closing_styles") or []
    if not styles:
        return ""
    avoid = recent_styles[-max(1, min(len(styles) - 1, 5)):]
    pool = [s for s in styles if s not in avoid] or styles
    return pool[int(hashlib.sha1(f"{company}|{role}".encode("utf-8")).hexdigest(), 16) % len(pool)]


def load_history(path: Path | None) -> list[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8")) if path and path.exists() else []
    except (OSError, ValueError):
        return []


def save_history(path: Path | None, entry: dict, keep: int = 30) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps((load_history(path) + [entry])[-keep:], indent=2, ensure_ascii=False),
                    encoding="utf-8")


def check_letter(text: str, resume: dict, cfg: dict, jd_text: str | None = None,
                 quotes: list[str] | None = None, previous_closers: list[str] | None = None,
                 names: str = "", sources: list[str] | None = None,
                 ended: "tuple[str, date] | None" = None) -> list[str]:
    """Every reason this letter must not be used. An empty list means it passes. With jd_text, the letter
    must also be anchored to the job description by verbatim quotes (see quote_problems). `names` is the company and
    role: digits in them ("project44", "Engineer 2") are not claims, so they are allowed."""
    problems: list[str] = []
    n_words = len(words(text))
    lo, hi, n_par = cfg["length"]["words_min"], cfg["length"]["words_max"], cfg["length"]["paragraphs"]
    if not lo <= n_words <= hi:
        problems.append(f"{n_words} words; it must be {lo}-{hi}")
    if len(paragraphs(text)) != n_par:
        problems.append(f"{len(paragraphs(text))} paragraphs; it must be exactly {n_par}, separated by blank lines")
    low = _norm(text)
    for phrase in cfg["banned_phrases"]:
        if _norm(phrase) in low:
            problems.append(f"banned phrase: '{phrase}'")
    vis = visible_text(resume)
    extra = set(guard.numbers(text)) - set(guard.numbers(vis)) - set(guard.numbers(names))
    if extra:
        problems.append(f"numbers that are not on the visible resume: {sorted(extra)}")
    vocab = {guard.canon(w) for w in guard.bank_vocabulary(_visible_data(resume))}
    tokens = {t.rstrip(".").lower() for t in re.findall(r"[A-Za-z0-9+#.]+", text)}
    techs = sorted(t for t in tokens if t and guard.is_known_tech(t) and guard.canon(t) not in vocab)
    if techs:
        problems.append(f"technologies that are not on the visible resume: {techs}")
    if m := _SENSITIVE.search(text):
        problems.append(f"sensitive topic '{m.group(0)}' (answered only from the profile, never in a letter)")
    if m := _SELF_CLAIM.search(text):
        problems.append(f"claim about the candidate or an outcome that the resume does not state: '{m.group(0)}'")
    first = (paragraphs(text) or [""])[0]
    n_first = len([x for x in re.split(r"(?<=[.!?])\s+", first) if x.strip()])
    cap1 = (cfg.get("first_paragraph") or {}).get("max_sentences", MAX_FIRST_PARAGRAPH_SENTENCES)
    if n_first > cap1:
        problems.append(f"the first paragraph has {n_first} sentences; at most {cap1}: state the role and connect it to "
                        "your work, and do not summarise the job description")
    if _GREETING.match(text):
        problems.append("starts with a greeting; the greeting line ('Hello,') is added for you")
    if previous_closers and _squash(closing_line(text)) in {_squash(c) for c in previous_closers}:
        problems.append("the closing sentence is identical to the one in an earlier letter; word it differently")
    if jd_text is not None:
        problems += quote_problems(text, jd_text, quotes or [])
    problems += repeated_openers(text)
    if ended:                               # (company, last working day): that job is over, so past tense only
        from jobbot import tense
        from jobbot.profile import human_date
        problems += tense.letter_problems(text, ended[0], human_date(ended[1]))
    if unbacked := sorted((_word_set(text) & _OUTCOME_WORDS) - _word_set(vis)):
        problems.append(f"claims an improvement the resume does not state: {unbacked}")
    if jd_text is not None:
        wide = sorted((_word_set(text) & _BROADENING) - _word_set(jd_text))
        if wide:
            problems.append(f"wording broader than the job description says: {wide}; stay as close to the JD's own "
                            "meaning as possible")
    for src in sources or []:
        if span := copied_span(text, src):
            problems.append(f"copies the style sample / model letter word for word: '{span}'; use the tone, not the "
                            "sentences")
            break
    if _QUOTE_MARKS.search(text):
        problems.append("contains quotation marks: paraphrase the job description in natural words (the exact "
                        "phrases belong only in jd_quotes)")
    cap = (cfg.get("achievements") or {}).get("max_sentences_with_numbers", MAX_ACHIEVEMENT_SENTENCES)
    with_numbers = [x for x in re.split(r"(?<=[.!?])\s+", text)
                    if set(guard.numbers(x)) - set(guard.numbers(names))]
    if len(with_numbers) > cap:
        problems.append(f"{len(with_numbers)} sentences with numbers; describe at most {cap} achievements "
                        "(1-2), each with a line on why it matters for this role")
    if _PLACEHOLDER.search(text):
        problems.append("contains a placeholder such as [Company] or <name>")
    if _MARKDOWN.search(text):
        problems.append("contains markdown / list formatting; plain paragraphs only")
    return problems


def _word_set(text: str) -> set:
    return {t.lower().replace("\u2019", "'") for t in re.findall(r"[A-Za-z][A-Za-z'\u2019]*", text)}


def repeated_openers(text: str) -> list[str]:
    """No two sentences may start with the same two words ("I would ... / I would ...", "I also ... / I also ...")."""
    seen: dict = {}
    for sentence in re.split(r"(?<=[.!?])\s+|\n+", text):
        first = [w.lower() for w in re.findall(r"[A-Za-z0-9'\u2019-]+", sentence)[:2]]
        if len(first) == 2:
            seen[" ".join(first)] = seen.get(" ".join(first), 0) + 1
    return [f"{n} sentences start with '{opener}'; start each sentence differently"
            for opener, n in seen.items() if n > 1]


def copied_span(text: str, source: str, n: int = COPY_SPAN) -> str:
    """The first run of n words that appears in both the letter and the source, else ""."""
    mine = [w.lower() for w in words(text)]
    theirs = [w.lower() for w in words(source)]
    grams = {tuple(theirs[i:i + n]) for i in range(len(theirs) - n + 1)}
    for i in range(len(mine) - n + 1):
        if tuple(mine[i:i + n]) in grams:
            return " ".join(mine[i:i + n])
    return ""


def _squash(s: str) -> str:
    return re.sub(r"\s+", " ", _norm(s)).strip(" .,;:!?\"'()")


def quote_problems(text: str, jd_text: str, quotes: list[str]) -> list[str]:
    """Statements about the company must be anchored to the job description. The model lists the verbatim JD
    phrases it relied on (in its own field, never inside quotation marks in the letter); code checks every quote is
    really in the JD and that the letter still carries the quote's key words, paraphrased around them."""
    jd, letter = _squash(jd_text), _norm(text)
    good = []
    out: list[str] = []
    for q in quotes:
        sq = _squash(str(q))
        if len(sq.split()) < 2:
            continue
        if sq not in jd:
            out.append(f"jd_quotes entry is not in the job description: '{str(q)[:60]}'")
            continue
        keys = set(re.findall(r"[a-z]{4,}", sq))
        used = [w for w in keys if w in letter]
        if len(used) >= min(2, len(keys)):                  # the letter paraphrases; it keeps the quote's key nouns
            good.append(q)                                  # a quote the paraphrase dropped just does not count
    if len(good) < MIN_QUOTES:
        out.append(f"fewer than {MIN_QUOTES} verbatim job-description quotes anchor the letter (jd_quotes)")
    return out


def _visible_data(resume: dict) -> dict:
    from jobbot.answers import visible_resume
    return visible_resume(resume)


def build_prompt(company: str, role: str, jd_text: str, resume: dict, cfg: dict, samples: list[str],
                 problems: list[str] | None = None, closing: str = "", model: str = "",
                 ended: "tuple[str, date] | None" = None) -> str:
    rules = "\n".join(f"- {r}" for r in cfg["style_rules"])
    banned = ", ".join(f'"{p}"' for p in cfg["banned_phrases"])
    shown = "\n\n".join(f"--- tone sample {i} ---\n{s}" for i, s in enumerate(samples, 1))
    retry = ("\nYOUR PREVIOUS ATTEMPT WAS REJECTED. Fix every one of these problems:\n"
             + "\n".join(f"- {p}" for p in problems) + "\n") if problems else ""
    tense = ""
    if ended:
        from jobbot.profile import human_date
        tense = (f"\nTENSE: the candidate's job at {ended[0]} ENDED on {human_date(ended[1])}. Describe it in the PAST tense "
                 f"only (\"At {ended[0]}, I owned...\", \"I led...\"). Never call it the current or present position, never write "
                 f"currently / presently / now about it, never \"I work at {ended[0]}\", and no present-tense verbs for what "
                 f"was done there (not \"I own\", \"I lead\", \"I manage\"). The resume dates below already show the end month.\n")
    L = cfg["length"]
    cap1 = (cfg.get("first_paragraph") or {}).get("max_sentences", MAX_FIRST_PARAGRAPH_SENTENCES)
    main = (f"""
MAIN STYLE MODEL: a cover letter the candidate wrote himself. Match its structure, rhythm, sentence length,
politeness and the way it opens and closes more than anything else. TONE ONLY: take NO facts, skills, employers or
sentences from it, and never reuse {COPY_SPAN} words in a row:
<<<
{model.strip()}
>>>
""") if model.strip() else ""
    return f"""You are writing a short cover letter for a job application. Do not use any tools. Reply with ONE JSON
object only, no prose, no code fences:
{{"letter": "<the letter>", "jd_quotes": ["<verbatim phrase from the job description>", "..."]}}

JOB: {role} at {company}

JOB DESCRIPTION:
<<<
{jd_text.strip()[:6000]}
>>>

THE CANDIDATE'S RESUME. This is the ONLY source of facts about the candidate:
{visible_text(resume)}

HOW TO WRITE
{rules}
- Exactly {L['paragraphs']} short paragraphs separated by one blank line, {L['words_min']}-{L['words_max']} words in total
  (aim for about {(L['words_min'] + L['words_max']) // 2 - 10} words; under {L['words_min']} is rejected, so write the why-it-matters lines in full).
  No greeting line, no sign-off, no subject line (they are added for you). Plain text: no markdown, no lists.
- Tone: confident and professional, never eager. Show interest through specific connections to the role, not through
  enthusiasm words. Never write "love to", "eager to", "excited to", "would be thrilled", "dream", or "please reach out".
- Paragraph 1 is AT MOST {cap1} sentences: state your intent plainly ("I'm applying for the {role} role at {company}.")
  and connect the role to your own work in one clause or sentence (the work you have done that bears on it). Do NOT summarise
  or restate the job description to the company: they wrote it. No list of what the role involves.
  Paragraph 1 is short (about 35 words), so paragraph 2 carries the letter: 120-140 words, in full sentences, and
  paragraph 3 about 30 words, for a total of about 190. A letter under {L['words_min']} words is rejected: count before answering.
  Paragraph 2 (all achievements stay inside this one paragraph; never a fourth paragraph): pick ONE or TWO achievements from the resume bullets above (never three or more, and not a list), using
  the real numbers exactly as written there. For each one say what you did, then one plain sentence on why it matters
  for THIS role. Do that naturally: put the fact beside the requirement it answers, in the same sentence or the next one,
  and never announce the link. No signpost sentences such as "This matters for your role because", "It fits well
  with", "This matches your", "This is close to". Paragraph 3: a simple, polite close in the tone of the writing samples, with
  one thank-you (the sign-off line is added for you, so do not add another). Do not write "In an interview" or
  "I would like to discuss".
- Stay as close to the job description's own meaning as possible. Do not broaden, generalise or add scope or
  superlatives: if it says "customers", do not write "the world's customers"; do not write global, worldwide,
  entire, industry-leading, best, everyone, always or similar unless the job description says exactly that.
- No two sentences may start with the same two words (not "I would ... / I would ...", not "I also ... / I also ...").
- NEVER put words in quotation marks in the letter. Paraphrase the job description in natural wording; the exact
  phrases go only in "jd_quotes".
- Mention the company only using facts stated in the job description. Do not invent anything about it, and do not
  use anything you know about the company from elsewhere. Every statement about the company or the role must rest on a
  short phrase copied EXACTLY from the job description; list at least {MIN_QUOTES} such phrases in "jd_quotes" and
  keep their key nouns in the letter, reworded around them. If you cannot quote it, do not say it.
- Say only what the resume above states. No feelings, lessons or personality claims ("I enjoy...", "this taught me...",
  "I like to...") and no results the resume does not state. Do not use words like faster, easier, improved, improves,
  speed, efficiency or fewer to describe what your work achieved unless the resume above uses that very word:
  describe what you DID (built, wired, owned), not what it led to.
- Vary the wording. Plain, direct sentences; no exclamation marks.
- HOW TO END (paragraph 3, one or two sentences, in your own words, not copied from this instruction): {closing or "a simple close and a thank-you"}
- Name only technologies that appear in the resume above. Never mention salary, visa, notice period,
  relocation or personal characteristics.
- Never use these phrases: {banned}
{retry}{main}{tense}
WRITING SAMPLES (use them ONLY for sentence length and plain wording. They are outdated and more eager than the letter
should be: take NO facts, skills, job titles or employers, no enthusiasm phrases ("love to", "excited", "eager"), and do
not copy their long technology lists or openers):
{shown}
"""


def generate(company: str, role: str, jd_text: str, resume: dict, cfg: dict, samples: list[str],
             llm: Callable[[str], dict], attempts: int = 2, closing: str = "",
             previous_closers: list[str] | None = None, model: str = "",
             ended: "tuple[str, date] | None" = None) -> LetterResult:
    """Ask for a letter; if the guard rejects it, ask once more with the reasons. Never returns a failing letter."""
    result = LetterResult(text=None, ok=False)
    problems: list[str] | None = None
    for _ in range(attempts):
        try:
            reply = llm(build_prompt(company, role, jd_text, resume, cfg, samples, problems, closing, model, ended))
            text = str(reply.get("letter", "")).strip()
            quotes = [str(q) for q in reply.get("jd_quotes") or []]
        except Exception as e:                               # Claude unavailable: no letter, never a guess
            if type(e).__name__ == "UsageLimitError":          # the limit is not a bad letter: stop and say so
                raise
            result.attempts.append({"text": "", "problems": [f"LLM call failed: {type(e).__name__}: {e}"[:200]]})
            break
        problems = (check_letter(text, resume, cfg, jd_text, quotes, previous_closers, f"{company} {role}",
                                 list(samples) + ([model] if model else []), ended) if text
                    else ["empty reply"])
        result.attempts.append({"text": text, "problems": problems, "jd_quotes": quotes})
        if not problems:
            result.text, result.ok = text, True
            break
    return result


# ─── PDF ─────────────────────────────────────────────────────────────────────

_TEX_ESC = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
            "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def full_letter(resume: dict, body: str) -> str:
    """What goes into a text box (and onto the PDF): greeting + the checked body + a sign-off."""
    return "\n".join(["Hello,", "", body.strip(), "", "Best regards,", resume["name"]])


def tex_escape(text: str) -> str:
    return "".join(_TEX_ESC.get(c, c) for c in text)


def letter_tex(resume: dict, body: str) -> str:
    """Same class and fonts as the resume (resume-openfont: Lato/Raleway), header like the resume's."""
    paras = "\n\n".join(tex_escape(p) for p in paragraphs(body))
    return "\n".join([
        r"\documentclass[]{resume-openfont}", r"\pagestyle{fancy}", r"\resetHeaderAndFooter",
        r"\setlength{\parindent}{0pt}", r"\setlength{\parskip}{0.9em}", r"\begin{document}",
        r"\begin{center}",
        rf"    \Huge \scshape \latoRegular{{{tex_escape(resume['name'])}}} \\ \vspace{{1pt}}",
        rf"    \small \href{{mailto:{resume['email']}}}{{\underline{{{tex_escape(resume['email'])}}}}}  $|$  "
        rf"{tex_escape(resume['phone'])}",
        r"\end{center}", r"\vspace{1.2em}", r"\fontsize{11pt}{15pt}\selectfont",
        "Hello,", "", paras, "", "Best regards,", r"\\", tex_escape(resume["name"]), r"\end{document}", ""])


def render_pdf(resume: dict, body: str, build_dir: Path, out_pdf: Path) -> Path:
    import shutil
    import tailor
    pdf, pages = tailor.compile_pdf(letter_tex(resume, body), build_dir)
    if pages != 1:
        raise tailor.TailorError(f"cover letter PDF is {pages} pages; it must be one")
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(pdf, out_pdf)
    return out_pdf


# ─── the provider the answer pipeline calls ─────────────────────────────────

def _saved_letter(job_dir: Path, resume: dict) -> "str | None":
    """The body of the letter a previous run saved in this job folder, or None."""
    f = Path(job_dir) / "cover_letter.txt"
    try:
        text = f.read_text(encoding="utf-8").strip() if f.exists() else ""
    except OSError:
        return None
    head, tail = "Hello,", f"Best regards,\n{resume.get('name', '')}"
    if not (text.startswith(head) and text.endswith(tail)):
        return None
    return text[len(head):-len(tail)].strip() or None


def _hard_problems(text: str, resume: dict, cfg: dict, ended, names: str) -> list[str]:
    """The guard for a letter being reused: every rule except 'the quotes anchor it to the JD' and the closing-repeat
    history (the letter was already accepted once, and is already in that history)."""
    return check_letter(text, resume, cfg, None, None, None, names, None, ended)


def make_provider(job_dir: Path, company: str, role: str, jd_text: str, resume: dict, llm: Callable[[str], dict],
                  cfg: dict | None = None, samples: list[str] | None = None,
                  renderer: Callable[[dict, str, Path, Path], Path] = render_pdf,
                  history_path: "Path | None" = None, model: "str | None" = None,
                  ended: "tuple[str, date] | None" = None):
    """field -> (value, note). value is the letter text (text box) or the PDF path (file upload), or None when
    the letter could not be produced. One letter per job: generated on first use, reused for every field.
    `history_path` remembers the closing style and closing sentence of recent letters so the next letter
    ends differently (default: output/_cover_letter_closings.json)."""
    cfg = cfg or load_config()
    samples = samples if samples is not None else load_samples()[0]
    model = load_model() if model is None else model
    if history_path is None:
        import tailor
        history_path = tailor.OUTPUT_DIR / "_cover_letter_closings.json"
    cache: dict = {}

    def provider(f) -> tuple["str | None", str]:
        if "res" not in cache and (saved := _saved_letter(job_dir, resume)) \
                and not _hard_problems(saved, resume, cfg, ended, f"{company} {role}"):
            cache["res"] = LetterResult(text=saved, ok=True, attempts=[{"text": saved, "problems": [], "reused": True}])
            cache["reused"] = True
        if "res" not in cache:
            history = load_history(history_path)
            closing = choose_closing(cfg, company, role, [h.get("style", "") for h in history])
            cache["res"] = generate(company, role, jd_text, resume, cfg, samples, llm, closing=closing,
                                    previous_closers=[h.get("closing", "") for h in history], model=model,
                                    ended=ended)
            job_dir.mkdir(parents=True, exist_ok=True)
            (job_dir / "cover_letter_attempts.json").write_text(
                json.dumps(cache["res"].attempts, indent=2, ensure_ascii=False), encoding="utf-8")
            if cache["res"].ok and not cache.get("reused"):
                (job_dir / "cover_letter.txt").write_text(full_letter(resume, cache["res"].text) + "\n",
                                                          encoding="utf-8")
                save_history(history_path, {"company": company, "style": closing,
                                            "closing": closing_line(cache["res"].text)})
        res: LetterResult = cache["res"]
        if not res.ok:
            return None, "; ".join(res.problems)[:300] or "no letter produced"
        if f.type == "file":
            if "pdf" not in cache:
                try:
                    cache["pdf"] = renderer(resume, res.text, job_dir / "_cover_build", job_dir / "cover_letter.pdf")
                except Exception as e:
                    cache["pdf"] = e
            if isinstance(cache["pdf"], Exception):
                return None, f"PDF render failed: {type(cache['pdf']).__name__}"
            return str(cache["pdf"]), "guard passed (%d attempt%s)" % (len(res.attempts), "s" if len(res.attempts) > 1 else "")
        return full_letter(resume, res.text), "guard passed (%d attempt%s)" % (len(res.attempts), "s" if len(res.attempts) > 1 else "")

    return provider
