"""M4 cover letters: text + one-page PDF, generated by Claude, checked by code.

Rules (plan.md, "Cover letters"):
  - 3 short paragraphs, 150-250 words, plain and specific. Tone comes from writing_samples.txt; facts come
    ONLY from the visible resume content (never from the samples, never invented).
  - The guard is code, not the LLM: word count, paragraph count, banned phrases (cover_letter.yaml), every
    number must exist on the visible resume, every technology named must be on the visible resume, no
    sensitive topics (salary, visa, notice, relocation, EEO), no placeholders or markdown.
  - A letter that fails is regenerated ONCE, with the reasons. Still failing -> no letter: an optional field is
    left empty, a required field switches that application to assist mode (handled in answers.py).
  - Every attempt is saved in the job folder.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

import yaml

import guard
from jobbot.answers import visible_text

ROOT = Path(__file__).resolve().parents[1]
CONFIG_FILE = ROOT / "cover_letter.yaml"
SAMPLES_FILE = ROOT / "writing_samples.txt"
SAMPLES_EXAMPLE = ROOT / "writing_samples.example.txt"

_SENSITIVE = re.compile(r"\b(salary|ctc|lpa|lakhs?|compensation|visa|sponsor\w*|work permit|notice period|"
                        r"relocat\w*|gender|ethnic\w*|veteran|disabilit\w*|authori[sz]ed to work|"
                        r"criminal|citizenship)\b", re.I)
# Statements about the candidate himself or about results that the resume does not make. The resume bullets are
# the only source of facts, so feelings, lessons and unstated outcomes are claims too.
_SELF_CLAIM = re.compile(r"\b(taught me|i (have )?learn(ed|t)|learn(ed|t) to|i (really |truly )?(love|like|enjoy|care about|"
                         r"believe|pride myself)|my passion|i am (someone|a person|a (quick|fast) learner)|"
                         r"(much|significantly|dramatically|greatly|vastly) (faster|better|easier|more (reliable|efficient)))\b", re.I)
MAX_LOVE_TO = 2          # "I would love to" is the user's phrase, but not three times in one letter
MIN_QUOTES = 2
_PLACEHOLDER = re.compile(r"\[[^\]\n]{1,40}\]|<[^>\n]{1,40}>|\{\{|\}\}|\bTODO\b|lorem ipsum", re.I)
_MARKDOWN = re.compile(r"(^|\n)\s*([#>*\-] |\d+\. )|\*\*|`|__")
_WORD = re.compile(r"[A-Za-z0-9][A-Za-z0-9'’+#./-]*")


@dataclass
class LetterResult:
    text: str | None
    ok: bool
    attempts: list[dict] = field(default_factory=list)       # [{"text":..., "problems": [...]}]

    @property
    def problems(self) -> list[str]:
        return self.attempts[-1]["problems"] if self.attempts else []


def load_config(path: Path = CONFIG_FILE) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def parse_samples(text: str) -> list[str]:
    body = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("#"))
    parts = re.split(r"^=== Sample[^\n]*$", body, flags=re.M)
    return [p.strip() for p in parts[1:] if p.strip()]


def load_samples(path: Path = SAMPLES_FILE) -> tuple[list[str], str]:
    """(samples, which file). Falls back to the made-up example, which still shows the format."""
    if path.exists():
        return parse_samples(path.read_text(encoding="utf-8")), path.name
    return parse_samples(SAMPLES_EXAMPLE.read_text(encoding="utf-8")), SAMPLES_EXAMPLE.name


def _norm(s: str) -> str:
    return s.replace("’", "'").replace("‘", "'").casefold()


def words(text: str) -> list[str]:
    return _WORD.findall(text)


def paragraphs(text: str) -> list[str]:
    return [p.strip() for p in re.split(r"\n\s*\n", text.strip()) if p.strip()]


def last_sentence(text: str) -> str:
    """The final sentence of the letter body (its closing line)."""
    parts = re.split(r"(?<=[.!?])\s+", paragraphs(text)[-1]) if paragraphs(text) else [""]
    return parts[-1].strip()


def choose_closing(cfg: dict, company: str, role: str, recent_styles: list[str]) -> str:
    """A closing style that differs from the letters written most recently. Deterministic for a given job."""
    import hashlib
    styles = cfg.get("closing_styles") or []
    if not styles:
        return ""
    avoid = recent_styles[-max(1, min(len(styles) - 1, 5)):]
    pool = [s for s in styles if s not in avoid] or styles
    return pool[int(hashlib.sha1(f"{company}|{role}".encode("utf-8")).hexdigest(), 16) % len(pool)]


def load_history(path: Path | None) -> list[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8")) if path and path.exists() else []
    except (OSError, ValueError):
        return []


def save_history(path: Path | None, entry: dict, keep: int = 30) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps((load_history(path) + [entry])[-keep:], indent=2, ensure_ascii=False),
                    encoding="utf-8")


def check_letter(text: str, resume: dict, cfg: dict, jd_text: str | None = None,
                 quotes: list[str] | None = None, previous_closers: list[str] | None = None) -> list[str]:
    """Every reason this letter must not be used. An empty list means it passes. With jd_text, the letter
    must also be anchored to the job description by verbatim quotes (see quote_problems)."""
    problems: list[str] = []
    n_words = len(words(text))
    lo, hi, n_par = cfg["length"]["words_min"], cfg["length"]["words_max"], cfg["length"]["paragraphs"]
    if not lo <= n_words <= hi:
        problems.append(f"{n_words} words; it must be {lo}-{hi}")
    if len(paragraphs(text)) != n_par:
        problems.append(f"{len(paragraphs(text))} paragraphs; it must be exactly {n_par}, separated by blank lines")
    low = _norm(text)
    for phrase in cfg["banned_phrases"]:
        if _norm(phrase) in low:
            problems.append(f"banned phrase: '{phrase}'")
    vis = visible_text(resume)
    extra = set(guard.numbers(text)) - set(guard.numbers(vis))
    if extra:
        problems.append(f"numbers that are not on the visible resume: {sorted(extra)}")
    vocab = {guard.canon(w) for w in guard.bank_vocabulary(_visible_data(resume))}
    tokens = {t.rstrip(".").lower() for t in re.findall(r"[A-Za-z0-9+#.]+", text)}
    techs = sorted(t for t in tokens if t and guard.is_known_tech(t) and guard.canon(t) not in vocab)
    if techs:
        problems.append(f"technologies that are not on the visible resume: {techs}")
    if m := _SENSITIVE.search(text):
        problems.append(f"sensitive topic '{m.group(0)}' (answered only from the profile, never in a letter)")
    if m := _SELF_CLAIM.search(text):
        problems.append(f"claim about the candidate or an outcome that the resume does not state: '{m.group(0)}'")
    if low.count("i would love to") > MAX_LOVE_TO:
        problems.append(f"'I would love to' used {low.count('i would love to')} times; at most {MAX_LOVE_TO}")
    if previous_closers and _squash(last_sentence(text)) in {_squash(c) for c in previous_closers}:
        problems.append("the closing sentence is identical to the one in an earlier letter; word it differently")
    if jd_text is not None:
        problems += quote_problems(text, jd_text, quotes or [])
    if _PLACEHOLDER.search(text):
        problems.append("contains a placeholder such as [Company] or <name>")
    if _MARKDOWN.search(text):
        problems.append("contains markdown / list formatting; plain paragraphs only")
    return problems


def _squash(s: str) -> str:
    return re.sub(r"\s+", " ", _norm(s)).strip(" .,;:!?\"'()")


def quote_problems(text: str, jd_text: str, quotes: list[str]) -> list[str]:
    """Statements about the company must be anchored to the job description. The model lists the verbatim JD
    phrases it relied on; code checks every quote is really in the JD and really used in the letter."""
    jd, letter = _squash(jd_text), _norm(text)
    good = []
    out: list[str] = []
    for q in quotes:
        sq = _squash(str(q))
        if len(sq.split()) < 2:
            continue
        if sq not in jd:
            out.append(f"jd_quotes entry is not in the job description: '{str(q)[:60]}'")
            continue
        used = [w for w in re.findall(r"[a-z]{4,}", sq) if w in letter]
        if len(used) >= 2:
            good.append(q)
        else:
            out.append(f"jd_quotes entry is not used in the letter: '{str(q)[:60]}'")
    if len(good) < MIN_QUOTES:
        out.append(f"fewer than {MIN_QUOTES} verbatim job-description quotes anchor the letter (jd_quotes)")
    return out


def _visible_data(resume: dict) -> dict:
    from jobbot.answers import visible_resume
    return visible_resume(resume)


def build_prompt(company: str, role: str, jd_text: str, resume: dict, cfg: dict, samples: list[str],
                 problems: list[str] | None = None, closing: str = "") -> str:
    rules = "\n".join(f"- {r}" for r in cfg["style_rules"])
    banned = ", ".join(f'"{p}"' for p in cfg["banned_phrases"])
    shown = "\n\n".join(f"--- tone sample {i} ---\n{s}" for i, s in enumerate(samples, 1))
    retry = ("\nYOUR PREVIOUS ATTEMPT WAS REJECTED. Fix every one of these problems:\n"
             + "\n".join(f"- {p}" for p in problems) + "\n") if problems else ""
    L = cfg["length"]
    return f"""You are writing a short cover letter for a job application. Do not use any tools. Reply with ONE JSON
object only, no prose, no code fences:
{{"letter": "<the letter>", "jd_quotes": ["<verbatim phrase from the job description>", "..."]}}

JOB: {role} at {company}

JOB DESCRIPTION:
<<<
{jd_text.strip()[:6000]}
>>>

THE CANDIDATE'S RESUME. This is the ONLY source of facts about the candidate:
{visible_text(resume)}

HOW TO WRITE
{rules}
- Exactly {L['paragraphs']} short paragraphs separated by one blank line, {L['words_min']}-{L['words_max']} words in total.
  No greeting line, no sign-off, no subject line (they are added for you). Plain text: no markdown, no lists.
- Paragraph 1: the role, and in one or two plain sentences what you would love to work on there (from the JD).
  Paragraph 2: connect 1-2 specific JD requirements to 1-2 concrete things from the resume bullets above, using the
  real numbers exactly as written there. Paragraph 3: a simple close and one thank-you (the sign-off line is added for you, so do not add another).
- Mention the company only using facts stated in the job description. Do not invent anything about it, and do not
  use anything you know about the company from elsewhere. Every statement about the company or the role must rest on a
  short phrase copied EXACTLY from the job description; list at least {MIN_QUOTES} such phrases in "jd_quotes" and use
  their key words in the letter. If you cannot quote it, do not say it.
- Say only what the resume above states. No feelings, lessons or personality claims ("I enjoy...", "this taught me...",
  "I like to...") and no results the resume does not state (for example "much faster").
- Vary the wording and use "I would love to" at most {MAX_LOVE_TO} times.
- HOW TO END (paragraph 3, one or two sentences, in your own words, not copied from this instruction): {closing or "a simple close and a thank-you"}
- Name only technologies that appear in the resume above. Never mention salary, visa, notice period,
  relocation or personal characteristics.
- Never use these phrases: {banned}
{retry}
WRITING SAMPLES (TONE ONLY: sentence length, politeness, word choice, how they close. They are outdated; take NO
facts, skills, job titles or employers from them, and do not copy their long technology lists or openers):
{shown}
"""


def generate(company: str, role: str, jd_text: str, resume: dict, cfg: dict, samples: list[str],
             llm: Callable[[str], dict], attempts: int = 2, closing: str = "",
             previous_closers: list[str] | None = None) -> LetterResult:
    """Ask for a letter; if the guard rejects it, ask once more with the reasons. Never returns a failing letter."""
    result = LetterResult(text=None, ok=False)
    problems: list[str] | None = None
    for _ in range(attempts):
        try:
            reply = llm(build_prompt(company, role, jd_text, resume, cfg, samples, problems, closing))
            text = str(reply.get("letter", "")).strip()
            quotes = [str(q) for q in reply.get("jd_quotes") or []]
        except Exception as e:                               # Claude unavailable: no letter, never a guess
            result.attempts.append({"text": "", "problems": [f"LLM call failed: {type(e).__name__}: {e}"[:200]]})
            break
        problems = (check_letter(text, resume, cfg, jd_text, quotes, previous_closers) if text
                    else ["empty reply"])
        result.attempts.append({"text": text, "problems": problems, "jd_quotes": quotes})
        if not problems:
            result.text, result.ok = text, True
            break
    return result


# ─── PDF ─────────────────────────────────────────────────────────────────────

_TEX_ESC = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
            "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def full_letter(resume: dict, body: str) -> str:
    """What goes into a text box (and onto the PDF): greeting + the checked body + a sign-off."""
    return "\n".join(["Hello,", "", body.strip(), "", "Best regards,", resume["name"]])


def tex_escape(text: str) -> str:
    return "".join(_TEX_ESC.get(c, c) for c in text)


def letter_tex(resume: dict, body: str) -> str:
    """Same class and fonts as the resume (resume-openfont: Lato/Raleway), header like the resume's."""
    paras = "\n\n".join(tex_escape(p) for p in paragraphs(body))
    return "\n".join([
        r"\documentclass[]{resume-openfont}", r"\pagestyle{fancy}", r"\resetHeaderAndFooter",
        r"\setlength{\parindent}{0pt}", r"\setlength{\parskip}{0.9em}", r"\begin{document}",
        r"\begin{center}",
        rf"    \Huge \scshape \latoRegular{{{tex_escape(resume['name'])}}} \\ \vspace{{1pt}}",
        rf"    \small \href{{mailto:{resume['email']}}}{{\underline{{{tex_escape(resume['email'])}}}}}  $|$  "
        rf"{tex_escape(resume['phone'])}",
        r"\end{center}", r"\vspace{1.2em}", r"\fontsize{11pt}{15pt}\selectfont",
        "Hello,", "", paras, "", "Best regards,", r"\\", tex_escape(resume["name"]), r"\end{document}", ""])


def render_pdf(resume: dict, body: str, build_dir: Path, out_pdf: Path) -> Path:
    import shutil
    import tailor
    pdf, pages = tailor.compile_pdf(letter_tex(resume, body), build_dir)
    if pages != 1:
        raise tailor.TailorError(f"cover letter PDF is {pages} pages; it must be one")
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(pdf, out_pdf)
    return out_pdf


# ─── the provider the answer pipeline calls ─────────────────────────────────

def make_provider(job_dir: Path, company: str, role: str, jd_text: str, resume: dict, llm: Callable[[str], dict],
                  cfg: dict | None = None, samples: list[str] | None = None,
                  renderer: Callable[[dict, str, Path, Path], Path] = render_pdf,
                  history_path: "Path | None" = None):
    """field -> (value, note). value is the letter text (text box) or the PDF path (file upload), or None when
    the letter could not be produced. One letter per job: generated on first use, reused for every field.
    `history_path` remembers the closing style and closing sentence of recent letters so the next letter
    ends differently (default: output/_cover_letter_closings.json)."""
    cfg = cfg or load_config()
    samples = samples if samples is not None else load_samples()[0]
    if history_path is None:
        import tailor
        history_path = tailor.OUTPUT_DIR / "_cover_letter_closings.json"
    cache: dict = {}

    def provider(f) -> tuple["str | None", str]:
        if "res" not in cache:
            history = load_history(history_path)
            closing = choose_closing(cfg, company, role, [h.get("style", "") for h in history])
            cache["res"] = generate(company, role, jd_text, resume, cfg, samples, llm, closing=closing,
                                    previous_closers=[h.get("closing", "") for h in history])
            job_dir.mkdir(parents=True, exist_ok=True)
            (job_dir / "cover_letter_attempts.json").write_text(
                json.dumps(cache["res"].attempts, indent=2, ensure_ascii=False), encoding="utf-8")
            if cache["res"].ok:
                (job_dir / "cover_letter.txt").write_text(full_letter(resume, cache["res"].text) + "\n",
                                                          encoding="utf-8")
                save_history(history_path, {"company": company, "style": closing,
                                            "closing": last_sentence(cache["res"].text)})
        res: LetterResult = cache["res"]
        if not res.ok:
            return None, "; ".join(res.problems)[:300] or "no letter produced"
        if f.type == "file":
            if "pdf" not in cache:
                try:
                    cache["pdf"] = renderer(resume, res.text, job_dir / "_cover_build", job_dir / "cover_letter.pdf")
                except Exception as e:
                    cache["pdf"] = e
            if isinstance(cache["pdf"], Exception):
                return None, f"PDF render failed: {type(cache['pdf']).__name__}"
            return str(cache["pdf"]), "guard passed (%d attempt%s)" % (len(res.attempts), "s" if len(res.attempts) > 1 else "")
        return full_letter(resume, res.text), "guard passed (%d attempt%s)" % (len(res.attempts), "s" if len(res.attempts) > 1 else "")

    return provider
